apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - elasticsearch.yaml
  - kibana.yaml
  - logstash.yaml
  - filebeat.yaml

commonLabels:
  app: elk-stack