apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: tcp
      host: "0.0.0.0:5044"
      enabled: true

    output.logstash:
      hosts: ["logstash:5514"]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.11.3
        args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat
        ports:
        - containerPort: 5044
          hostPort: 5044
          protocol: TCP
      volumes:
      - name: config
        configMap:
          name: filebeat-config
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: logging
spec:
  selector:
    app: filebeat
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
  type: NodePort